export { allModels, realPair } from "./catalog-helpers.ts";
export {
  extractDeclarations,
  normalizeSource,
  type SourceHashGateOptions,
  sourceHashGate,
} from "./source-hash-gate.ts";
export {
  allowMarked,
  type CallInfo,
  callbackBodiesOf,
  collectAwaits,
  collectCalls,
  collectDestructurings,
  collectElementAccess,
  collectImports,
  collectMemberAccess,
  type DestructuringInfo,
  type ElementAccessInfo,
  type ImportBinding,
  type ImportInfo,
  importBindings,
  lineOf,
  type MemberAccessInfo,
  parseSource,
  resolveImportedFunctionBody,
  resolveTypeAliases,
  sameFileFunctionBodies,
  transitiveRelativeImports,
  typedBindings,
  walk,
} from "./ts-scan.ts";
